### ISSUE TITLE
"Cannot locate Wing standard library" in Playground 

### ISSUE THREAD

**Issue by eladb** [winglang/wing#1718]
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

https://playground.winglang.io/

### I expected this:

To work

### Instead, this happened:

```
Compilation failed with 1 error(s)
Error at :1:1 | Cannot locate Wing standard library
```

### Component:

Other

**Comment by Chriscbr** [comment]
Waiting for the release to see if this is actually fixed

**Comment by monadabot** [comment]
Congrats! :rocket: This was released in [Wing 0.5.87](https://github.com/winglang/wing/releases/tag/v0.5.87).

**Comment by Chriscbr** [comment]
It looks like reverting #1684 did indeed fix the playground
