### ISSUE TITLE
`Cannot find module 'typedarray-to-buffer'` in 0.24.12

### ISSUE THREAD

**Issue by MarkMcCulloh** [winglang/wing#3388]
### Incident description

See https://github.com/winglang/wing/pull/3386

Regression from https://github.com/winglang/wing/pull/3367

### Is there a workaround?

No reasonable workaround (downgrade wing version)

### Incident Response Checklist

- [X] CREATE this issue (fill up the title, description and submit), then follow the next steps.
- [x] PIN the incident issue.
- [X] ACKNOWLEDGE the incident on [PagerDuty](https://monada.pagerduty.com/incidents).
- [X] ACKNOWLEDGE the incident on [BetterStack](https://uptime.betterstack.com/team/48207/incidents).
- [X] WORKAROUND - if there is one, make sure it is documented in the section above.
- [x] PRIORITIZE (P0/P1/P2 - see the definitions [here](https://www.winglang.io/contributing/maintainers/operations#severity-levels)).
- [x] (optional) CONTACT a relevant person who has more information about the incident.
- [x] (optional) ANNOUNCE major incidents on Slack \#dev or \#general channels. "NOTICE - P0 incident started. {incident-description}. Track on {link to issue}".
- [x] HANDLE by reverting or forward fixing.
- [ ] UPDATE the team on your actions in the created \#alert Slack thread throughout the incident.
- [ ] RESOLVE the incident on [PagerDuty](https://monada.pagerduty.com/incidents) (BetterStack resolves automatically).
- [ ] UPDATE the team on the issue closure.
- [ ] (optional) ANNOUNCE closure of major incidents on Slack \#dev or \#general channels. "NOTICE - P0 incident ended. {incident-resolution-description}. Track on {link to issue}".
- [ ] UNPIN the incident issue.
- [ ] LESSONS LEARNED should be shared via the "post-mortem" workflow on \#dev Slack channel.
- [ ] CLOSE the incident issue.

**Comment by MarkMcCulloh** [comment]
@ekeren Yes

**Comment by MarkMcCulloh** [comment]
Followup to prevent this in the future https://github.com/winglang/wing/issues/3390

Fixed in https://github.com/winglang/wing/pull/3386
