### PR TITLE
feat(build): autopublish wing cli spec to fig

### LINKED ISSUE #2631: Auto update fig spec for wing CLI whenever the CLI changes
### Feature Spec

#768 added support for wing CLI in fig. However this got outdated quickly (see the file in their repo [here](https://github.com/withfig/autocomplete/blob/master/src/wing.ts)). We should use the [Push To Autocomplete Action](https://fig.io/docs/guides/integrating/push-to-autocomplete-action) and automatically update fig spec whenever there is a change in wing CLI.

### Use Cases

Having an up-to-date support for wing CLI in fig

### Implementation Notes

We should use the [Push To Autocomplete Action](https://fig.io/docs/guides/integrating/push-to-autocomplete-action).

### Component

CLI

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by fynnfluegge**
Adds wing cli fig spec publish step in build workflow whenever wing cli changes.

Downgrades `commander:10.0.0` to `commander:8.0.0` since `@fig/complete-commander` requires commander v8. 

Closes #2631.

## Checklist
- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: .github/workflows/build.yml [hunk 1]
```diff
@@ -78,12 +81,32 @@ jobs:
...
+
       - name: Upload Wing CLI
         uses: actions/upload-artifact@v3
         with:
           name: wing
           path: apps/wing/*.tgz
 
+      - name: Generate the fig spec
+        if: ${{ steps.git-diff-wing-cli.outputs.diff == 'true' }}
+        run: cd apps/wing && node dist/cli.js generate-fig-spec >> new-fig-cli-generated.ts
```
Comment (MarkMcCulloh) [inline .github/workflows/build.yml:101]: idea: What if this process runs in a separate workflow with a release trigger? Then it can just use the cli directly from npm to generate this spec.

File: apps/wing/package.json [hunk 2]
```diff
@@ -29,22 +29,23 @@
     "unbump": "node unversion.js"
   },
   "dependencies": {
+    "@winglang/sdk": "file:../../libs/wingsdk",
     "chalk": "^4.1.2",
     "codespan-wasm": "0.3.0",
-    "commander": "^10.0.0",
+    "commander": "^8.0.0",
```
Comment (MarkMcCulloh) [inline apps/wing/package.json:35]: I'm not sure we're okay with downgrading our dependency so much just to satisfy the peer dependency of @fig/complete-commander. Looks like it's all contained in this single file https://github.com/withfig/autocomplete-tools/blob/main/integrations/commander/src/index.ts. Maybe we can just copy/paste with attribution instead, assuming it still works with the latest version of commander.

**Review by MarkMcCulloh — CHANGES_REQUESTED** [review]

File: apps/wing/package.json (hunk 2 above)
Comment (fynnfluegge) [reply apps/wing/package.json:35]: True, I had also mixed feelings about this, will try to tweak this with commander 10 instead

File: tools/hangar/package.json [hunk 3]
```diff
@@ -12,13 +12,14 @@
   "author": "Monada",
   "license": "Apache-2.0",
   "devDependencies": {
+    "@cdktf/provider-aws": "^12.0.13",
+    "@fig/complete-commander": "^2.0.1",
```
[the remark this answers is not in the document]
Comment (fynnfluegge) [reply tools/hangar/package.json:16]: I added this because [here](https://github.com/winglang/wing/actions/runs/5135713161/jobs/9242301503) the test failed with `Error: Cannot find module '@fig/complete-commander'`

File: .github/workflows/build.yml (hunk 1 above)
Comment (fynnfluegge) [reply .github/workflows/build.yml:99]: Fyi: once https://github.com/winglang/wing/pull/2755 is successfully merged I will apply the same technique with `nrwl/nx-set-shas@v3` action here

**Comment by fynnfluegge** [comment]
Hey @MarkMcCulloh I think this looks good now. I added the `do-not-merge` label because I am going to test this soon by adding a temporary trigger to the fig publish workflow in this PR.

**Comment by fynnfluegge** [comment]
Hey @MarkMcCulloh I changed the fig generation workflow to test it in this PR, going to test the generator first and finally test the PR trigger to the fig repo. But the workflows are blocked, is it due to  requested changes?

**Comment by MarkMcCulloh** [comment]
@fynnfluegge I think github was having issues syncing/running workflows. Now it's also not running because there are conflicts.

**Comment by fynnfluegge** [comment]
Hey @MarkMcCulloh, I finally found time to test this. It looks promising ✅
Here https://github.com/winglang/wing/actions/runs/5611732892/job/15203877048 we can see that the fig code generation still works fine with `commander:10.0.0`
I use `npm root -g` to get the path of the global npm path after doing `npm i -g winglang` to get to the location of `cli.js`. I tested this here https://github.com/winglang/wing/actions/runs/5613374481/job/15209270817.

Last question: should the target still be `main` since here are no changes that affect any wing code or do we want to merge this into `dev`?

File: apps/wing/tsconfig.json [hunk 4]
```diff
@@ -22,6 +22,7 @@
     "declaration": true,
     "baseUrl": ".",
     "esModuleInterop": true,
+    "types": ["@withfig/autocomplete-types"]
```
Comment (MarkMcCulloh) [inline apps/wing/tsconfig.json:25]: How is this used?

File: apps/wing/src/commands/figSpec.ts [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+const DEFAULT_FIG_SUBCOMMAND_NAME = "generate-fig-spec";
+
+function convertDefaultValue(v: unknown) {
+  if (typeof v === "string") return v;
+  if (Array.isArray(v)) return v.join(",");
+  return String(v);
+}
+
+function getTemplate(spec: Fig.Spec): string {
+  return prettier.format(
```
[the remark this answers is not in the document]
Comment (fynnfluegge) [reply apps/wing/src/commands/figSpec.ts:17]: Tested this without prettier, but it looks bad unfortunately 😕
```
// Autogenerated by @fig/complete-commander

    const completionSpec: Fig.Spec = {"name":"wing","subcommands":[{"name":["run","it"],"description":"Runs a Wing program in the Wing Console","options":[{"name":["-p","--port"],"description":"specify port","args":{"name":"port"}},{"name":["--no-open"],"description":"Do not open the Wing Console in the browser"},{"name":["-h","--help"],"description":"display help for command","priority":49}],"args":[{"name":"entrypoint","description":"program .w entrypoint","isOptional":true}]},{"name":"lsp","description":"Run the Wing language server on stdio","options":[{"name":["-h","--help"],"description":"display help for command","priority":49}]},{"name":"compile","description":"Compiles a Wing program","options":[{"name":["-t","--target"],"description":"Target platform","args":{"name":"target","suggestions":["tf-aws","tf-azure","tf-gcp","sim","awscdk"],"default":"sim"}},{"name":["-p","--plugins"],"description":"Compiler plugins","args":{"name":"plugin","isOptional":true,"isVariadic":true}},{"name":["-h","--help"],"description":"display help for command","priority":49}],"args":[{"name":"entrypoint","description":"program .w entrypoint"}]},{"name":"test","description":"Compiles a Wing program and runs all functions with the word 'test' or start with 'test:' in their resource identifiers","options":[{"name":["-t","--target"],"description":"Target platform","args":{"name":"target","suggestions":["tf-aws","tf-azure","tf-gcp","sim","awscdk"],"default":"sim"}},{"name":["-p","--plugins"],"description":"Compiler plugins","args":{"name":"plugin","isOptional":true,"isVariadic":true}},{"name":["-h","--help"],"description":"display help for command","priority":49}],"args":[{"name":"entrypoint","description":"all entrypoints to test","isVariadic":true}]},{"name":"docs","description":"Open the Wing documentation","options":[{"name":["-h","--help"],"description":"display help for command","priority":49}]},{"name":"help","description":"display help for command","priority":49,"args":{"name":"command","isOptional":true,"template":"help"}}],"options":[{"name":["-V","--version"],"description":"output the version number"},{"name":["--debug"],"description":"Enable debug logging (same as DEBUG=1)"},{"name":["--progress"],"description":"Show compilation progress"},{"name":["--no-progress"],"description":"Hide show compilation progress"},{"name":["--no-update-check"],"description":"Skip checking for toolchain updates"},{"name":["--no-analytics"],"description":"Disable analytics collection (same as WING_DISABLE_ANALYTICS=1)"},{"name":["-h","--help"],"description":"display help for command","priority":49}]}

    export default completionSpec;
```

File: apps/wing/tsconfig.json (hunk 4 above)
Comment (fynnfluegge) [reply apps/wing/tsconfig.json:25]: This is needed for `Fig.Arg` and `Fig.Option`

Comment (MarkMcCulloh) [reply apps/wing/tsconfig.json:25]: You should be able to do something like `import type { Arg, Option } from "@withfig/autocomplete-types"` (you may have to alias them) instead of adding the type here.

File: apps/wing/src/commands/figSpec.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (MarkMcCulloh) [reply apps/wing/src/commands/figSpec.ts:17]: Does looking bad matter? I assumed this file is simply used internally, do users actually see this

[the remark this answers is not in the document]
Comment (fynnfluegge) [reply apps/wing/src/commands/figSpec.ts:17]: Actually not, but I guess this will be the content of the PR in the fig repo, so it's a matter of how the maintainers will accept this, but however, we can try it. I don't mind, I can remove the `prettier.format` and then lets see how the PR will look like

File: apps/wing/tsconfig.json (hunk 4 above)
Comment (fynnfluegge) [reply apps/wing/tsconfig.json:25]: I also tried, pnpm build works with this, but then the command `node dist/cli.js generate-fig-spec >> test.ts` does not find `@withfig/autocomplete-types` 😕
So I found this https://github.com/withfig/autocomplete-tools/blob/main/types/README.md and it worked. I also don't like the compilerOptions param, but didn't find a workaround.

File: apps/wing/src/commands/figSpec.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (MarkMcCulloh) [reply apps/wing/src/commands/figSpec.ts:17]: Yeah that would be preferable, it seems pretty wasteful to force the `prettier` dependency for all consumers of the CLI when it's only used for this.

File: apps/wing/src/commands/figSpec.ts
Comment (MarkMcCulloh) [inline apps/wing/src/commands/figSpec.ts:1]: Add a simple unit test that ensures the new subcommand doesn't explode. Adding a snapshot test here also would be reasonable imo.

File: .github/workflows/publish-fig-spec.yml [hunk 6]
```diff
@@ -0,0 +1,54 @@
+name: Publish Fig Completion Spec
+
+on:
+  pull_request_target:
+    types:
+      - opened
+      - synchronize
+      - reopened
+      - edited
```
Comment (MarkMcCulloh) [inline .github/workflows/publish-fig-spec.yml:9]: Is this trigger just for testing? As the workflow is written I'm not sure it makes sense to run in PRs

```suggestion
```

File: .github/workflows/publish-fig-spec.yml [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+
+      - name: Create Autocomplete PR
+        if: ${{ steps.git-diff-wing-cli.outputs.diff == 'true' }}
+        uses: withfig/push-to-fig-autocomplete-action@v1
+        with:
+          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
+          autocomplete-spec-name: wing
+          spec-path: $(npm root -g)/winglang/dist/new-fig-cli-generated.ts
+          integration: commander
+          new-spec-version: ${{ steps.wing-version.outputs.version }}
```
Comment (MarkMcCulloh) [inline .github/workflows/publish-fig-spec.yml:54]: Does this action handle if the ts file is the same?

File: .github/workflows/publish-fig-spec.yml [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+on:
+  pull_request_target:
+    types:
+      - opened
+      - synchronize
+      - reopened
+      - edited
+  release:
+    types:
+      - published
```
Comment (MarkMcCulloh) [inline .github/workflows/publish-fig-spec.yml:12]: git diffing after a publish probably isn't a reliable way to check if something has changed. You'd probably have to execute the command on winglang@V2 and winglang@V1 and diff them.

Also, why not just generate the spec during the build? That way we don't have to execute anything here and you can just use https://docs.npmjs.com/cli/v7/commands/npm-diff to check if anything changed.

File: .github/workflows/publish-fig-spec.yml (hunk 7 above)
Comment (MarkMcCulloh) [reply .github/workflows/publish-fig-spec.yml:54]: If it does, we may not need to bother checking for a change at all
